- name: setup fileservers
  hosts: fileservers
  user: root
  
  roles:
    - common
    - fileserver
  sudo: yes
  vars_prompt:
    - name: "fileserver_password"
      prompt: "what is the fileserver password?"
      private: yes
