
# need module to format sdb1 if not already

- name: install xfsprogs
  apt: pkg=xfsprogs state=latest

- name: create xfs filesystem on /dev/sdb1
  filesystem: fstype=xfs dev=/dev/sdb1

- name: mkdir user storage dir
  file: path=/home/{{ user }}/storage owner={{ user }} group={{ user }} mode=0777 state=directory

- include: glusterfs.yml

- name: repriv user storage dir
  file: path=/home/{{ user }}/storage owner={{ user }} group={{ user }} mode=0777 state=directory
