- name: add apt signing key for gluster
  apt_key: url=http://download.gluster.org/pub/gluster/glusterfs/3.4/3.4.0/Debian/pubkey.gpg state=present

- name: add apt repository for gluster
  apt_repository: repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.4/3.4.0/Debian/apt wheezy main' state=present

- name: update package list
  apt: update_cache=yes

- name: install glusterfs client
  apt: pkg=glusterfs-client state=latest

- name: install glusterfs server
  apt: pkg=glusterfs-server state=latest

- name: mkdir /export/partition
  file: path=/export/{{item.part}} state=directory
  with_items: disks

- name: mount gluster partition as a brick
  mount: name=/export/{{item.part}} src=/dev/{{item.part}} fstype={{item.fstype}} state=mounted
  with_items: disks

- name: mkdir /export/partition/brick
  file: path=/export/{{item.part}}/brick state=directory
  with_items: disks

- name: see if gluster volume already created
  shell: "gluster volume info | grep \"^Volume Name: {{name}}$\""
  register: gluster_volume_created
  ignore_errors: True

- name: setup a gluster volume
  shell: gluster volume create {{name}}
  when: (not gluster_volume_created.stdout)

- name: add bricks to gluster volume
  shell: gluster volume add-brick {{name}} {{name}}.{{domain}}:/export/{{item.dev}}{{item.part}}/brick
  when: (not gluster_volume_created.stdout)
  with_items: disks

- name: see if gluster volume already started
  shell: "gluster volume info {{name}} | grep \"^Status: Started$\""
  register: gluster_volume_started
  ignore_errors: True

- name: start the gluster volume
  shell: gluster volume start {{name}}
  when: (not gluster_volume_started.stdout)

- name: mount the gluster volume
  mount: name=/home/{{user}}/storage src={{name}}.{{domain}}:{{name}} fstype=glusterfs state=mounted

- name: change permission of volume
  file: path=/home/{{user}}/storage owner={{user}} group={{user}} state=directory
