- name: setup repo for raid utils
  apt_repository: repo="deb http://hwraid.le-vert.net/debian wheezy main"

- name: setup repo key for raid utils
  apt_key: url=http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key state=present

- name: install 3ware raid utils
  apt: pkg=tw-cli state=latest update_cache=yes

