- name: install rsync
  apt: pkg=rsync state=latest

- name: install inetd
  apt: pkg=openbsd-inetd state=latest

- name: configure inetd for rsync
  lineinfile: dest=/etc/inetd.conf regexp=^rsync line="rsync stream tcp nowait {{ user }} /usr/sbin/tcpd /usr/bin/rsync --daemon"
  notify:
    - restart inetd

- name: create run dir in user dir
  file: path=/home/{{ user }}/run owner={{ user }} group={{ user }} mode=0700 state=directory

- name: create log dir in user dir
  file: path=/home/{{ user }}/log owner={{ user }} group={{ user }} mode=0700 state=directory

- name: start inetd
  service: name=openbsd-inetd state=started

- name: configure rsyncd
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf backup=yes
